global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  
  # - job_name: "fastapi"
  #   static_configs:
  #     - targets: ["192.168.1.4:9182"]
  #       labels:
  #         app: "ai-devops-monitor"
  #         env: "production"

  # Dynamic targets from UI
  - job_name: "dynamic-targets"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets.json"
        refresh_interval: 30s

