global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  # Your FastAPI app (self-monitoring)
  - job_name: "fastapi"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          app: "ai-devops-monitor"
          env: "production"

  # Dynamic targets from UI
  - job_name: "dynamic-targets"
    file_sd_configs:
      - files:
          - "targets.json"
        refresh_interval: 30s

